services:
  app:
    image: dbproj-app
    networks:
      - dbproj-network
    ports:
      - "127.0.0.1:5000:5000"
    build: ./app/
    restart: no

  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./storage/db:/var/lib/mysql:z
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - dbproj-network
    restart: no
    
  valkey:  
    image: valkey/valkey:8-alpine
    volumes:
      - ./storage/valkey/:/usr/local/etc/valkey/
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - dbproj-network

networks:
  dbproj-network:
    driver: bridge
