[PERMISSIONS]
"requests_bp.moneyperclient" = ["admin", "manager"]
"requests_bp.accountsfromtodate" = ["admin", "manager"]

"clients_bp.index" = ["admin"]
"clients_bp.edit" = ["admin"]
"clients_bp.create" = ["admin"]

"external_bp.remain" = ["regular"]
"external_bp.transfer" = ["regular"]

"reports_bp.index" = ["admin", "stat"]
"reports_bp.create" = ["admin"]
"reports_bp.view" = ["admin", "stat"]