# Example config

SECRET_KEY = 'random'

[DATABASE]
host = 'mariadb'
port = 3306
user = 'root'
pass = 'root'
name = 'course'

[PERMISSIONS]
"requests_bp.moneyperclient" = ["admin"]
"requests_bp.accountsfromtodate" = ["admin"]
"external_bp.remain" = ["regular"]