# Example config

SECRET_KEY = 'random'

[DATABASE]
host = 'mariadb'
port = 3306
user = 'root'
pass = 'root'
name = 'course'

[PERMISSIONS]
"app.requests.moneyperclient" = ["admin"]
"app.requests.accountsfromtodate" = ["admin"]
"app.external.remain" = ["regular"]